# -*- coding: utf-8 -*-
"""day10partc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-sb2047DmLluYHk8lu06D3QhVaIfH6D

## Part C — Interview Ready

### Q1: Conceptual

**LEGB Rule**

Python resolves variable names using the **LEGB rule**:

L → Local  
E → Enclosing  
G → Global  
B → Built-in  

Python searches for a variable in this order.

Example:

```python
x = "global"

def outer():
    x = "enclosing"

    def inner():
        x = "local"
        print(x)

    inner()

outer()

Output:

local

Python finds x in the local scope of inner() first.

Scope Diagram

Built-in Scope
    |
Global Scope
    |
Enclosing Scope (outer function)
    |
Local Scope (inner function)

Python searches from Local → Enclosing → Global → Built-in.

Same Variable in Local and Global

If a variable exists in both local and global scope, Python uses the local variable.

Example:

x = 10

def func():
    x = 20
    print(x)

func()
print(x)

Output:

20
10

The function uses its local x, not the global one.

global Keyword

The global keyword allows a function to modify a global variable.

Example:

count = 0

def update():
    global count
    count += 1

Why global is a Code Smell

Using global is discouraged because:

It breaks function independence

Makes code harder to debug

Introduces hidden side effects

Reduces modularity

Better Alternatives

Pass variables as function arguments

Return values instead of modifying globals

Use classes or objects

Use closures

Example:

def update(count):
    return count + 1
"""

#Q2: Coding — Memoization Decorator
from functools import wraps

def memoize(func):
    cache = {}

    @wraps(func)
    def wrapper(*args):
        if args in cache:
            return cache[args]

        result = func(*args)
        cache[args] = result
        return result

    return wrapper


@memoize
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)


print(fibonacci(50))

"""Explanation

A dictionary cache stores computed results.

Function arguments are used as the key.

If the same arguments appear again, the stored value is returned instead of recomputing.

Without memoization, fibonacci(50) would take extremely long due to repeated recursive calls.
With memoization, the result is computed once and reused, making it almost instantaneous.
"""

