# -*- coding: utf-8 -*-
"""Stretch Problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_bG5M3uv4SMX7ePvz3bzWf50C7Tjjgl
"""

import time
from functools import wraps


# Timer Decorator
def timer(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()

        result = func(*args, **kwargs)

        end = time.time()
        print(f"Execution time of {func.__name__}: {round(end - start, 4)} seconds")

        return result
    return wrapper


# Logger Decorator
def logger(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print(f"Calling function: {func.__name__}")
        print(f"Arguments: args={args}, kwargs={kwargs}")

        result = func(*args, **kwargs)

        print(f"Return value: {result}")
        return result
    return wrapper


# Retry Decorator
def retry(max_attempts=3):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            attempts = 0

            while attempts < max_attempts:
                try:
                    return func(*args, **kwargs)
                except Exception as e:
                    attempts += 1
                    print(f"Attempt {attempts} failed: {e}")

                    if attempts == max_attempts:
                        print("Max retry attempts reached.")
                        raise
        return wrapper
    return decorator


# Example usage

@timer
@logger
def add(a, b):
    return a + b


@retry(max_attempts=3)
def unstable_function(x):
    if x < 5:
        raise ValueError("Input must be >= 5")
    return x * 2


print(add(3, 4))

try:
    print(unstable_function(2))
except Exception:
    print("Function failed after retries")

