# -*- coding: utf-8 -*-
"""student_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m85a1C_6VQRlnIhUE0Xc4n4OvO8tkLyC
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile student_analytics.py
# from collections import defaultdict
# from typing import Dict, List
# 
# def create_student(name: str, roll: str, **marks: int) -> dict:
#     return {
#         "name": name,
#         "roll": roll,
#         "marks": marks if marks else {},
#         "attendance": 0.0
#     }
# 
# def calculate_gpa(*marks: float, scale: float = 10.0) -> float:
#     if not marks:
#         return 0.0
#     avg = sum(marks) / len(marks)
#     return round((avg / 100) * scale, 2)
# 
# def get_top_performers(students: List[dict], n: int = 5, subject: str = None) -> List[dict]:
#     if not students:
#         return []
# 
#     def score(student):
#         marks = student.get("marks", {})
#         if subject:
#             return marks.get(subject, 0)
#         return sum(marks.values()) / len(marks) if marks else 0
# 
#     return sorted(students, key=score, reverse=True)[:n]
# 
# def generate_report(student: dict, **options) -> str:
#     include_grade = options.get("include_grade", True)
#     verbose = options.get("verbose", False)
# 
#     name = student.get("name", "Unknown")
#     roll = student.get("roll", "NA")
#     marks = student.get("marks", {})
# 
#     avg = sum(marks.values()) / len(marks) if marks else 0
# 
#     if avg >= 90:
#         grade = "A"
#     elif avg >= 75:
#         grade = "B"
#     elif avg >= 60:
#         grade = "C"
#     else:
#         grade = "D"
# 
#     report = f"Student: {name} ({roll}) | Average: {round(avg,2)}"
# 
#     if include_grade:
#         report += f" | Grade: {grade}"
# 
#     if verbose:
#         report += f" | Marks: {marks}"
# 
#     return report
# 
# def classify_students(students: List[dict]) -> dict:
#     result = defaultdict(list)
# 
#     for s in students:
#         marks = s.get("marks", {})
#         if not marks:
#             continue
# 
#         avg = sum(marks.values()) / len(marks)
# 
#         if avg >= 90:
#             grade = "A"
#         elif avg >= 75:
#             grade = "B"
#         elif avg >= 60:
#             grade = "C"
#         else:
#             grade = "D"
# 
#         result[grade].append(s)
# 
#     return dict(result)



