# -*- coding: utf-8 -*-
"""test_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eY53wClOK36HgLJsQ9MMu-Wgf9Q3kv4i
"""

from student_analytics import *

s1 = create_student("Amit", "R001", math=85, python=92, ml=78)
s2 = create_student("Priya", "R002", math=95, python=88, ml=91)
s3 = create_student("Rahul", "R003", math=60, python=65, ml=70)

students = [s1, s2, s3]


# create_student tests
assert s1["name"] == "Amit"
assert s1["marks"]["python"] == 92
assert isinstance(s1, dict)


# calculate_gpa tests
assert calculate_gpa(85, 92, 78) > 0
assert calculate_gpa() == 0
assert round(calculate_gpa(100, 100), 2) == 10.0


# get_top_performers tests
top = get_top_performers(students, n=1)
assert len(top) == 1
assert top[0]["name"] == "Priya"

top_python = get_top_performers(students, n=1, subject="python")
assert top_python[0]["name"] == "Amit"


# generate_report tests
rep = generate_report(s1)
assert "Amit" in rep

rep2 = generate_report(s1, verbose=True)
assert "Marks" or "marks" in rep2

rep3 = generate_report(s1, include_grade=False)
assert "Grade" not in rep3


# classify_students tests
grades = classify_students(students)
assert isinstance(grades, dict)
assert "A" in grades or "B" in grades or "C" in grades or "D" in grades
assert len(grades) > 0

